
import "./globals.css";
import { ThemeProvider } from './context/ThemeContext';
import DashboardLayout from '@/components/dashboard/DashboardLayout';



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
